### ISSUE TITLE
PHP 5.6.x compatability

### ISSUE THREAD

**Issue by avcascade** [meitar/tumblr-crosspostr#20]
For future reference, Tumblr Crosspostr gives the following warnings when being activated in a PHP 5.6.x environment:

```
Warning: Invalid argument supplied for foreach() in /home/someuser/somesite/wp-content/plugins/tumblr-crosspostr/tumblr-crosspostr.php on line 77

Warning: Cannot modify header information - headers already sent by (output started at /home/someuser/somesite/wp-content/plugins/tumblr-crosspostr/tumblr-crosspostr.php:77) in /home/someuser/somesite/wp-includes/option.php on line 772

Warning: Cannot modify header information - headers already sent by (output started at /home/someuser/somesite/wp-content/plugins/tumblr-crosspostr/tumblr-crosspostr.php:77) in /home/someuser/somesite/wp-includes/option.php on line 773
```
These warnings are not seen when activating in a PHP 5.5.x environment.

**Comment by meitar** [comment]
Hm. Are you sure this is actually a difference in PHP? [Line 77 of the current release as of this filing](https://github.com/meitar/tumblr-crosspostr/blob/0.8.2/tumblr-crosspostr.php#L77) is inside a pretty old migration function. Is it possible you activated the plugin on PHP 5.6.x but then used the same database when activating from a PHP 5.5.x? If so, it's probable this issue is simply a minor bug in Tumblr Crosspostr, not a difference with PHP's behavior in `foreach` loops.

**Comment by meitar** [comment]
This isn't a compatibility issue, it's just a different symptom caused by #21.
