### ISSUE TITLE
Replace Tumblr Crosspostr's support for Tumblr Queue with scheduled posts

### ISSUE THREAD

**Issue by spirograph** [meitar/tumblr-crosspostr#25]
When you queue a post on Tumblr, it has a post ID. However, when that queued post comes _out_ of the queue, it is assigned a _different_ post ID.

This makes full post sync difficult if I'm using post scheduling on the Wordpress side - whenever I sync posts from Tumblr, I end up with duplicates of every post I'd used the schedule/queue for! (The way I use the crossposter requires me to be able to sync posts in both directions.)

I don't think you'll be able to fix this about Tumblr, but what I'd like is for Tumblr Crosspostr to have an option not to use the Tumblr queue. I only want it to crosspost when the Wordpress post actually goes live. Is this technically possible?

**Comment by meitar** [comment]
> However, when that queued post comes out of the queue, it is assigned a different post ID.

Augh, fucking Tumblr.

[If it's true that Tumblr also supports scheduled posts](https://wordpress.org/support/topic/scheduling-posts-on-wordpress-issue?replies=4) (like WordPress does) by simply setting the publication date to a future time, this may be reason enough for me to rework Crosspostr's logic for handling future-dated posts on Tumblr by bypassing the Queue altogether.

@spirograph Would you consider removing support for Tumblr's queue and replacing it wholesale with a WordPress-like Scheduled Posts feature a fix or does this break something for your use case?

**Comment by spirograph** [comment]
Yeah, Tumblr does have a scheduled posts function; the only problem with it is [its interface](http://freyayuki.tumblr.com/post/111971879507/problem-tumblr-schedule-posts-date-time), which presumably won't be a problem if it's getting automated. In fact, if you schedule a post, it ends up in the Queue interface *anyway*, so there's less change in interface than you'd expect.

As far as I can tell, that won't break anything. It's almost certainly going to be better, even - by removing the queue, this means that the timing of the queue no longer overrides the timing of Wordpress scheduling.

**Comment by meitar** [comment]
Good reference: https://wordpress.org/support/topic/proper-scheduled-post-translation-work-in-progress?replies=1

**Comment by su** [comment]
<blockquote>Not sending them over to Tumblr would mean, for instance, not sending drafts over, because those aren't published, either. [etc. more work than worth etc.] </blockquote>

Yeah, that's pretty much what I'd thought, and I actually agree. But I wanted to put it out there in case anyone wants to try and argue for it.

In thinking about this since posting, I'm increasingly okay with the query URLs. They're ugly but don't break anything, and barring some pretty fundamental changes to WP should in fact be *more* robust than passing through the pretty ones, since they just get redirected to the current URL scheme, even if it changes later. But that still leaves the question of a full-on CMS switch, where these would definitely break. [pause for headdesk]

Of course it's your call whether that's an acceptable situation to eventually put out into a release. It's a small enough hack that I can just maintain it for my purposes for the time being.

**Comment by meitar** [comment]
> But that still leaves the question of a full-on CMS switch, where these would definitely break.

:) I mean, yes, but that's what URL rewriting is for, isn't it? Ultimately, there is nothing we can do to prevent someone from breaking their site or links to it. It's their site, after all.

Until the Web moves to something like [IPFS](https://ipfs.io/ipfs/QmNhFJjGcMPqpuYfxL62VVB9528NXqDNMFXiqN5bgFYiZ1/its-time-for-the-permanent-web.html), it's up to site owners to ensure their [cool URIs don't change](https://www.w3.org/Provider/Style/URI.html).

**Comment by meitar** [comment]
Fixed in 79a21ea78ae67e5f1c43408d508766c763660533.
