### ISSUE TITLE
Issue with reconnecting tumblr-crosspostr

### ISSUE THREAD

**Issue by Const4ntFlux** [meitar/tumblr-crosspostr#29]
So I installed and authenticated tumblr-crosspostr with tumblr and the next day, I see it posted all of the blog posts I edited (changed keyword within WP) to tumblr on account of me not switching the crosspost option to 'No'. My mistake. But not only that, it also posted my scheduled posts to tumblr before they were even published on my WP which is an issue for me.
I deleted all those posts on tumblr. Needless to say, tumblr-crosspostr can't republish them now because it (of course) gets a 404 from tumblr for those posts. Doh.
The I deactivated and deinstalled tumblr-crosspostr in the hope of deleting all data with it, basically resetting the whole thing and starting from scratch. After the reinstallation went through, I was again asked for oath and key from tumblr within tumblr-crosspostr's setup dialogue on WP, and it wouldn't accept (I enter oath and secret, click 'click here to connect to tumblr' and nothing happened). Then me, the noob, thought it needed a new app. I went to create a new app on tumblr, twice, to no avail.
I now have three apps on tumbler which I can't remove and a defunct tumblr-crosspostr.
Any chance to resolve this chaos would be much appreciated.
Thanks!

**Comment by meitar** [comment]
Wow, that sounds like an awful experience. :( You've unfortunately hit several frustrating issues with Tumblr's API in combination with some known bugs in Tumblr Crosspostr along with a few issues just misunderstanding Tumblr Crosspostr's current implementation in succession. Sympathies about that. Here's the detail:

> it also posted my scheduled posts to tumblr before they were even published on my WP which is an issue for me.

Tumblr Crosspostr was written before Tumblr supported scheduled posts, so all "scheduled" posts in WordPress are put in Tumblr's *queue*, and are *not* scheduled. This isn't a bug so much as it's just not yet implemented. See issue #25 for more information.

> I deleted all those posts on tumblr. Needless to say, tumblr-crosspostr can't republish them now because it (of course) gets a 404 from tumblr for those posts. Doh.

Tumblr Crosspostr augments your WordPress posts with metadata that associates which Tumblr post the given WordPress post was crossposted to. By default, uninstalling the plugin doesn't remove this data specifically so that if you ever re-install the plugin (or need to know which Tumblr post was created from your WP post) you can still look that information up. In your case, though, this is causing a problem because the post was deleted on the *Tumblr* side, not the WordPress side, and Tumblr doesn't have any mechanism to inform other programs that these deletions happen (which is precisely why my recommendation is to use WordPress, not Tumblr, to make edits to your Tumblr posts).

So you need to either manually remove or update these bits of metadata. This metadata is in the WordPress post's custom fields. See [this support forum post](https://wordpress.org/support/topic/ask-reblogs-missing-latest-reblog-comment/#post-6956740) for more info.

> After the reinstallation went through, I was again asked for oath and key from tumblr within tumblr-crosspostr's setup dialogue on WP, and it wouldn't accept (I enter oath and secret, click 'click here to connect to tumblr' and nothing happened).

This is a very frustrating issue and has to do with the way your server's PHP session store is handled. It's something a lot of people run into from time to time. See [this post in the support forum for a solution](https://wordpress.org/support/topic/click-here-to-connect-to-tumblr-not-working/page/2/#post-4723700).

> I now have three apps on tumbler which I can't remove

Yeah, I don't understand why Tumblr doesn't offer a way to remove apps. `¯\_(ツ)_/¯` Tumblr is really awful in a lot of ways.

**Comment by Const4ntFlux** [comment]
Quick reopen to say thank you for your patience and your kind and thorough reply.
Hopefully it came across that I was just stumped and looking for advice and not complaining (I'm fully aware that I navigated into this corner on my own).
Also: I'm hurdle racing the language track here. ;)
Keep up the good work and forthcoming communication! 👍

**Comment by Const4ntFlux** [comment]
I have run into a wall it seems. I can neither find the custom fields (tried installing several plug-ins to view custom fields, but couldn't get tumblr-crosspostrs to show up and edit them) and am generally unsure how to view the fields you mentioned.
Nor am I able to enter the oauth key and secret to chose the option to "leave no trace" deinstall as per your new version of tumblr-crosspostr to reinstall cleanly although I used the hint you linked to in your previous response. I can find no 'old' php_sessions directory to point php to. 
How can I erase the custom fields in the back-end safely, if at all?

**Comment by meitar** [comment]
You don't need a plugin to edit custom fields, just ensure they are visible in your [Screen Options](http://www.wpbeginner.com/glossary/screen-options/).

**Comment by Const4ntFlux** [comment]
Thanks! I found the option and deleted the fields.
After digging through the thread you linked, I found the [suggestion](https://wordpress.org/support/topic/click-here-to-connect-to-tumblr-not-working/#post-4723501) to clear cookies from the domain I'm running wordpress on, restarted the browser and now it is working a-ok. Thank you!
